version: "2"
services:
  mysql:
    image: mysql:5.7
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: permanence_etudiante
      MYSQL_USER: spf
      MYSQL_PASSWORD: dbpassword
    volumes:
      - ./storage/mysql:/var/lib/mysql
